### ISSUE TITLE
Kodlama

### ISSUE THREAD

**Issue by karamizrak** [kodlamaio-projects/nArchitecture.Core#11]
Paketlerdeki elastic, redis, logging vs starter projeye nasıl uyguluyoruz?

**Comment by EnesDONER** [comment]
Command veya Querylerinizi ILoggableRequest'den kalıtım alın. Bu bir pipeline otomatik olarak tüm işlemleri loglar. Kendi logunuzu yazmak için DI'dan ILogger'ı alın  _logger.Information("myLog")); ile log yazabilirsiniz.  ApplicationServiceRegistration'dan konfigürasyonuzu görebilirsiniz. Umarım yardımcı olmuştur.

**Comment by EnesDONER** [comment]
> Paketlerdeki elastic, redis, logging vs starter projeye nasıl uyguluyoruz?
Command veya Querylerinizi ILoggableRequest'den kalıtım alın. Bu bir pipeline otomatik olarak tüm işlemleri loglar. Kendi logunuzu yazmak için DI'dan ILogger'ı alın _logger.Information("myLog")); ile log yazabilirsiniz. ApplicationServiceRegistration'dan konfigürasyonuzu görebilirsiniz. Umarım yardımcı olmuştur.

**Comment by EnesDONER** [comment]
> Paketlerdeki elastic, redis, logging vs starter projeye nasıl uyguluyoruz?

Command veya Querylerinizi ILoggableRequest'den kalıtım alın. Bu bir pipeline otomatik olarak tüm işlemleri loglar. Kendi logunuzu yazmak için DI'dan ILogger'ı alın _logger.Information("myLog")); ile log yazabilirsiniz. ApplicationServiceRegistration'dan konfigürasyonuzu görebilirsiniz. Umarım yardımcı olmuştur.

**Comment by karamizrak** [comment]
Teşekkürler, deneyeceğim.
