### ISSUE TITLE
NArchitecture.Core.Security.DependencyInjection Version

### ISSUE THREAD

**Issue by furkanaltaca** [kodlamaio-projects/nArchitecture.Core#8]
An error occurs when star application;

Unhandled exception. System.TypeLoadException: Could not load type 'NArchitecture.Core.Security.JWT.ITokenHelper`2' from assembly 'Core.Security, Version=1.3.0.0, Culture=neutral, PublicKeyToken=null'.
   at NArchitecture.Core.Security.DependencyInjection.SecurityServiceRegistration.AddSecurityServices[TUserId,TOperationClaimId](IServiceCollection services)

I upgrade the packages but NArchitecture.Core.Security.DependencyInjection changed and didn't release for nuget. 
You should release new version for Core.Security.DependencyInjection, I think that the problem will solved.

**Comment by ahmet-cetinkaya** [comment]
You have to add new generic arguments to AddSecurityServices extension method.
