### ISSUE TITLE
Core.CrossCuttingConcerns.Exception.WebApi Throw always System.Exception (Http error code: 500)

### ISSUE THREAD

**Issue by furkanaltaca** [kodlamaio-projects/nArchitecture.Core#9]
The application always throws System.Exception without distinguishing between BusinessException or other error types and overload of the HandleException function. Do I need to do anything special to make this distinction?

I will cancel the nuget package, take the relevant layer from the Core projects, edit it and use it myself. I'm waiting for your advice. Kind regards.

**Comment by furkanaltaca** [comment]
I have opened a pull request for this issue: #10

**Comment by kazimkesler** [comment]
Bence de methodların ismini değiştirip switch-case yapısına girmek en mantıklısı. Ancak çok isteyen şu şekilde de çözebilir (Bunu önermiyorum ama sadece bir fikir olur diye paylaşıyorum)


```
dynamic underlyingException = exception switch
{
	BusinessException _businessException => _businessException,
	UnauthorizedException _unauthorizedException => _unauthorizedException,
	ForbiddenException _forbiddenException => _forbiddenException,
	ValidationException _validationException => _validationException,
	NotFoundException _notFoundException => _notFoundException,
	Exception _exception => _exception
};
await httpExceptionHandler.HandleException(underlyingException);
```

**Comment by kazimkesler** [comment]
Veya şöyle bir çözümde olabilir. Ama dedigim gibi method adlarını değiştirmek de fayda var :)
```
try
{
	await _next(httpContext);
}
catch (ValidationException exception)
{
	await HandleExceptionAsync(httpContext.Response, exception);
}
catch (Exception exception)
{
	await HandleExceptionAsync(httpContext.Response, exception);
}
```

**Comment by furkanaltaca** [comment]
Üstat yanlışım olabilir ama denediğim için şunu soracağım: İki kod yapısında da örnek olarak BusinessException geldiği zaman bu da bir System.Exception nesnesinden türetildiği veya miras alındığı için HandleExceptionAsync metodu her zaman System.Exception ile overload edilen metodu çalıştırıyor. 

Bu nedenle if else ile instance kontrolü yapıp HandleBusinessExceptionAsync gibi fonksiyon tanımlarıyla yaptım. 

Çalışır hale gelince böyle bir pr açtım. Siz kodu deneyip çalıştı diyorsanız ben de tekrardan deneyeceğim. 

Katkınız için teşekkür ederim.

**Comment by kazimkesler** [comment]
Zaten açtığın issue'da haklısın, böyle bir problem var zaten. Tam ben issue açmaya geliyordum sen açmışsın :) Yukarıdakiler sadece çözüm için alternatif yollar. Ben de isimleri değiştirerek yapmayı uygun gördüm.

**Comment by furkanaltaca** [comment]
:) Demek istediğim verdiğiniz çözüm örnekleri de aynı sorunu devam ettiriyor gibi geldi bana. Benzer kod yapısını denedim. Çalışmayınca overload edilen HandleException metodunun isimleriyle oynayarak çözüme gittim.

**Comment by kazimkesler** [comment]
Benim yazdiklarim isim degiştirmeden sorunu cözüyor. Denemezsem neden koyayim ki buraya

**Comment by furkanaltaca** [comment]
Şüphemi yanlış anlamayın lütfen. Bu tarz veya benzer bir yaklaşım denedim ve her seferinde System.Exception için tanımlanan metoda yönlendirdi. Bence bu iki yaklaşım daha iyi. Siz yeni pr oluşturun isterseniz. Ben burayı kapatayım.

Teşekkürler katkılarınız için.
